### PR TITLE
Add GitHub workflow for vaft

### PR DESCRIPTION
**Pull request by ElijahPepe**
Updating vaft-ublock-origin.js can be tedious. This PR adds a GitHub Action that runs daily. It then runs a shell script that does the following:

1. Access the GitHub API for recent commits to cleanlock/VideoAdBlockForTwitch.
2. If a commit was made today, continue. Otherwise, do nothing.
3. `cd` into vaft and download the latest version of remove_video_ads.js.
4. Add necessary text to the beginning and end of the file.
5. Beautify the file.

### CODE REVIEW

**Comment by ElijahPepe** [comment]
I've filed this as a draft in order to garner feedback on using GH Actions first. @pixeltris, if you have any thoughts?

**Comment by pixeltris** [comment]
A script would make sense as opposed to manually reformatting it. That being said automatically pulling it from the repo isn't the best idea for a few reasons:

- Only changes to `remove_video_ads.js` are important and non-logic changes can be skipped.
- Manually reviewing any changes will avoid automatically pulling in anything malicious if there's another incident. Additionally a relevant commit message could be provided for the given change.
- The original extension was essentially in maintenance mode. Most changes were edge cases / bug fixes and those were few and far between. I don't see there being many updates coming forth unless Twitch does something crazy.

I think what I'll do instead is add myself to the watch list of the repo and add some code to [utils.cs](https://github.com/pixeltris/TwitchAdSolutions/blob/master/utils.cs) to do something similar as your script which I'll manually run when there are relevant changes.

**Comment by cleanlock** [comment]
Basically what @pixeltris said. I don't think that there will be any major updates to the extension in the near future, unless Twitch decides to change the player once again. The last changes were all for the extension menu, so nothing major.

**Comment by pixeltris** [comment]
This has been added to utils.cs

**Pull request closed without merging**
