### PR TITLE
mute-black.user.js: rewrite with MutationObserver

### PR DESCRIPTION
**Pull request by Mathnerd314**
Out of the solutions, the mute-black seems the most appealing as Twitch will have a hard time detecting / blocking it. But when I looked at the code it was full of junk from the other solutions. Also, it used polling which seemed inefficient. So I cut out all the junk and rewrote the rest to use a MutationObserver. I tested it and it seems to work fine.

I guess I don't really expect you to merge this, but I wanted someplace to post my version...

### CODE REVIEW

**Comment by pixeltris** [comment]
The original code was [this](https://github.com/pixeltris/TwitchAdSolutions/blob/9ea57d0cebe92132c933f36811e383b3d997cb90/mute-black/mute-black-ublock-origin.js). It was taken from https://pastebin.com/HS9ukpRm (EthanShulman).

That polling resulted in some frames / audio coming through, so I pulled `mute-black` into the common script `base.user.js`, which allowed me to check for ads in the m3u8 before any DOM changes.

The `MutationObserver` change works great compared to polling, however I consistently see the first frame of the ad without the m3u8 detection (strangely with script from `master` some ad audio gets through, but no frames).

I'll need to do some more testing, ads are pretty sporadic for me these days which is annoying trying to test things. Perhaps some solution which starts the stream as muted/blacked out might be the most ideal for completely avoiding ad frames / audio.

**Comment by pixeltris** [comment]
The MutationObserver really works well, I've changed the code in the master branch to use it and it really helps at reducing ad audio/frame leaks.

I think removing additional code for something like `mute-black` makes sense. I think m3u8 detection is important to reduce the likelihood of ad frames/audio appearing. Possibly one way to do this without m3u8 is by checking the player elapsed time which can be done via the main browser context via DOM (see `reloadTwitchPlayer` / `player.state.position`). You could start muted/blacked out, and wait for ~1 second of `player.state.position` change before revealing the stream. This should ensure no ad frames / audio at any point.

**Comment by Mathnerd314** [comment]
Interesting, thanks for taking a look. So you're saying that the m3u8 stuff blacks out the ad too. I guess I missed that when I looked through the code before.

I'm not sure about video-player, I tried that and the ad didn't black out at all. But it's hard to test accurately because the ads are infrequent.

**Comment by pixeltris** [comment]
https://www.twitch.tv/twitchmedia28 is a useful page for testing (it always shows pre-roll ads), though on that stream I never see any frame/audio leak, but it's still a useful page for testing things.

[This](https://github.com/pixeltris/TwitchAdSolutions/blob/2424ab3cc1167a5e307ee03f042cdf83052040ac/base/base.user.js#L918) is the code I used for `video-player`. I did notice one time that the mute/black stayed active after the ad was complete, so there might be some issues with it.

For the m3u8 code path it broadcasts a message `UboFoundAdSegment` to the `window` scope which calls `onFoundAd`. As this happens prior to the player knowing that there are ads it helps reduce ad frames from appearing (but it's not perfect), possibly adding an additional 100ms delay before returning the m3u8 would make it perfect (or better yet; add confirmation of the `onFoundAd` call prior to returning the m3u8).

Alternatively replacing ad .ts files with a black .ts file might also be a decent solution, but that would require having a valid ts uploaded somewhere or embedded via a base64 encoded file string (which I'm not 100% sure if that would be valid).

Quite a few different directions `mute-black` could be taken, but I haven't gotten around to properly look into any of these mentioned things yet.

**Comment by Mathnerd314** [comment]
Checking it out more, I think the issue with using .video-player is that more video players are dynamically added. So if you start from the homepage and navigate to twitchmedia28 with the search bar then the code won't pick up the new video player. It'll black out because the old one was remove but it won't come back afterwards.

So this new version monitors `document` for `video-player`'s and then checks each video player for ads. Honestly the old version seemed fine, I don't think querying the document for a single class is that slow.

**Comment by Mathnerd314** [comment]
On a different note, I played around and found `findReactNode(reactRootNode, node => node.setPlayerMenuState);`. This has an `isVideoAdShowing` property. I think this is a more reliable method of detecting when there's an ad than checking for a span. There's probably also some way to hook `componentDidUpdate` to catch changes in this property, so that none of the DOM mutation stuff is needed.

**Comment by Mathnerd314** [comment]
Further investigation shows 7 react nodes with the property node.state.adEvents.addEventListener. This method takes two arguments, the second is a callback and the first can be (among others) 'AdError', 'Resumed', 'ContentResumeRequested', 'Loaded', 'Started', 'Impression', 'Complete', 'Skipped'. But I'm not sure why there are 7 nodes instead of just 1.

**Comment by pixeltris** [comment]
That's interesting about the `video-player` observer. If the original observer reduces issues and is less code that sounds more ideal.

Those react nodes sound interesting, though I'd assume they would trigger at the same time as the DOM element. But definitely worth checking out.

https://github.com/pixeltris/TwitchAdSolutions/commit/aca0ad8b7dfd11df966b00f1e04edc6f0f799d3e in this commit I added what I described above `"Alternatively replacing ad .ts files with a black .ts file might also be a decent solution"`. It's about 170 lines of code but currently it uses a ~30KB base64 encoded ts file, I'm sure that could be massively stripped down but I haven't really looked into it. It should currently show a loading circle (I think that .ts might actually be malformed...).

As for this PR I'm happy to merge it even with the minor frame leaking issues as I think a simple mute/black script has a lot of value on terms of longevity. Shall I merge it as-is or do you want to go back to the old observer? Or do a bit more looking around at the react stuff?

**Comment by Mathnerd314** [comment]
I've used it for a bit and I think the current state can be merged as-is. Maybe it should be under a new filename "simple-mute-black.user.js" instead of replacing the current one. The react stuff seems complicated - it'll probably have problems dealing with react tree mutations, and there's no react mutation observer like there is for the DOM.

**Comment by pixeltris** [comment]
Going to close this. Feel free to open a new PR (or just re-open this) if you want to pull this functionality in. The original script was removed as Twitch changed things around and I didn't care much to keep it updated.

**Comment by Mathnerd314** [comment]
Yeah,. I'm using TTV-LOL now as it's just a pain to deal with updates.

**Pull request closed without merging**
