### PR TITLE
Update vaft-ublock-origin.js

### PR DESCRIPTION
**Pull request by Zephiiro**
scope.PlayerType2 = 'autoplay'; //360p 
=> 
scope.PlayerType2 = 'embed'; //360p

### CODE REVIEW

**Comment by Zephiiro** [comment]
yes

**Comment by yungsamd17** [comment]
This change has fixed it ☑️

**Comment by TsukiZero** [comment]
Doesn't stop video-only freezes in the userscript version

**Comment by pixeltris** [comment]
Changed the script to prefer embed but fall back to 360p when embed also has an ad notifier https://github.com/pixeltris/TwitchAdSolutions/commit/c3663da4a9c62c87051e6666f57765319c0b3a3a

**Pull request closed without merging**
